### ISSUE TITLE
unsupported NetBIOS session service message type

### ISSUE THREAD

**Issue by Steinweber** [adobe/node-smb-server#3] opened 2016-11-25 20:01 UTC
Hi

if i wana connect to server, i see this msg

`error: [SMB] unsupported NetBIOS session service message type: 79`
by
[https://github.com/adobe/node-smb-server/blob/master/lib/smbconnection.js#L57](url)

I wana use this server as a pass through proxy. Is this somehow possible?

**Comment by stefan-guggisberg** [comment] 2016-12-06 16:44
please specify os version and client software used to connect to the SMB server.

WRT pass through proxy: could you please elaborate on your concrete use case?

**Comment by stefan-guggisberg** [comment] 2017-01-06 13:15
insufficient information provided to diagnose issue,  closing

**Comment by brandonros** [comment] 2017-02-26 06:34
OS version is Windows 7

Client is Windows Explorer

**Comment by Heronbeluci** [comment] 2017-10-24 14:13
i need help too

**Comment by Heronbeluci** [comment] 2017-10-24 14:23
im with Windows 10 and Windows Explorer too

**Comment by kkronyak** [comment] 2017-12-07 03:51
This appears to be caused by attempting to access the node SMB server using an alternative port (ex. \\[server]:8445\).  Windows tries to interpret this as a web URL and sends an HTTP request to the server.  Windows will only make outbound SMB connections on the standard port (445).  This could potentialy be worked around by using port translation on a firewall etc.

**Comment by stefan-guggisberg** [comment] 2018-12-17 19:21
as @kkronyak correctly pointed out, Windows SMB clients only support the standard SMB port `445`.

closing issue.

**Closed by stefan-guggisberg** 2018-12-17 19:21 UTC
